### ISSUE TITLE
LAN

### ISSUE THREAD

**Issue by Mrshadowzx** [MovTery/PojavZenithHorizon#100]
### Problem Description

The lan that the other player created does not appear.

### Log Files

No lag problem.

### Screenshots or Videos

![Screenshot_20240802-221716](https://github.com/user-attachments/assets/72b5dc8f-e4e0-4613-a413-4a49f8d8c44f)

![Screenshot_20240802-221426](https://github.com/user-attachments/assets/62083a00-f840-462e-9a4e-a00377f636bd)

### Steps to Reproduce

```markdown
After the lan is created, it is not visible to other players.
```

### Expected Behavior

Join the LAN to play with another player, without servers.

### Android Version

14

### Pojav Zenith Horizon Version

1.2.5.9

### Additional Information

```markdown
- Device Model:moto g54
- CPU Architecture:dimensity 7020
- GPU Information:PowerVR B-Series BXM-8-256
```

### This issue has not been reported by anyone else yet

- [X] I have checked the issues and have not found any similar reports

**Comment by Vera-Firefly** [comment]
Please make sure that you are in the same LAN, and your friends have added your LAN to the server list

**Comment by Vera-Firefly** [comment]
Here is a related [video](https://youtu.be/RlLsdP-F3lM?si=CyAHE4cCwwl2RqRr)

**Comment by edeninocencion0-ux** [comment]
Hey
