### ISSUE TITLE
离线玩家名称无法输入“.”字符

### ISSUE THREAD

**Issue by NoxArgenta** [MovTery/PojavZenithHorizon#103]
### 问题描述

![Screenshot_20240806_221634_net kdt pojavlaunch zh](https://github.com/user-attachments/assets/d4eacac9-2270-4cf0-a9aa-c7b8dda50be5)
如图，无法创建带有“.”的账户，实测PC端启动器可以创建含该字符的账户，希望PojavZenithHorizon能允许该字符，谢谢，辛苦了！

### 日志文件

![Screenshot_20240806_221634_net kdt pojavlaunch zh](https://github.com/user-attachments/assets/6b0dee79-09f8-4162-ba49-ffc3d4636b51)

### 截图或视频

![Screenshot_20240806_221634_net kdt pojavlaunch zh](https://github.com/user-attachments/assets/7349b31d-9aa2-476a-a550-5a26228b5a80)

### 复现步骤

```markdown
1、打开启动器
2、创建账户
3、local account
4、输入test.test
5、无法创建
```

### Android 版本

14

### Pojav Zenith Horizon 版本

1.2.6

### 其他信息

```markdown
- 设备型号：vivoS18
- CPU 架构：ARM
- GPU 信息：Qualcomm 7gen3
```

### 这个问题还没有人反馈过

- [X] 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by MovTery** [comment]
![image](https://github.com/user-attachments/assets/8660d66f-dcc0-43dd-9083-3c9add60d86d)
![image](https://github.com/user-attachments/assets/18e4f76d-6017-4eaa-b84a-3c53b65feb91)
![image](https://github.com/user-attachments/assets/2e147e9f-633c-45f8-b417-1daf70b4f855)
