### ISSUE TITLE
Better Mouse[Request] Brief Description

### ISSUE THREAD

**Issue by dudjv** [MovTery/PojavZenithHorizon#104]
### Feature Description

The actual mouse center of the custom added mouse image is now in the upper left corner of the imageCustomize the actual click mouse center at any position in the image

### This feature request has not been proposed before

- [X] I have checked the Issues and found no similar feature request

**Comment by dudjv** [comment]
I really want to have this feature

**Comment by MovTery** [comment]
No, the actual click position of the mouse is at the top-left corner of the mouse icon. This mechanism is designed to mimic the approach used by most PC systems, such as Windows. This helps users understand and use the mouse pointer more easily. If the pointer position of your mouse icon content is in the center, please adjust the position of the mouse icon content accordingly.

**Comment by dudjv** [comment]
> 不是，鼠标的实际点击位置是在鼠标图标的左上角。此机制旨在模仿大多数 PC 系统（例如 Windows）使用的方法。这有助于用户更轻松地理解和使用鼠标指针。如果您的鼠标图标内容的指针位置在中心，请相应地调整鼠标图标内容的位置。

我想要使用十字形的鼠标
