### ISSUE TITLE
Switch mouse within the game

### ISSUE THREAD

**Issue by dudjv** [MovTery/PojavZenithHorizon#105]
### 功能描述

Switch mouse function in the launcher menu within the game
Add dynamic mouse

### 这个功能建议还没有人提出过

- [X] 我已经查看过 Issues，并且没有发现与之类似的功能建议被提出

**Comment by MovTery** [comment]
You only need to add this mapped key to the control layout to dynamically switch the virtual mouse.
![IMG_20240807_175921](https://github.com/user-attachments/assets/2e5cde90-7ff4-4c11-b523-3783560e71c9)
![IMG_20240807_175936](https://github.com/user-attachments/assets/ba023866-5622-45e9-95a2-a783316b23e6)

**Comment by dudjv** [comment]
I mean switching between custom virtual mice within the game

> 只需要将此映射键添加到控制布局中，即可动态切换虚拟鼠标。 ![IMG_20240807_175921](https://private-user-images.githubusercontent.com/123115192/355769603-2e5cde90-7ff4-4c11-b523-3783560e71c9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjU4ODYsIm5iZiI6MTcyMzAyNTU4NiwicGF0aCI6Ii8xMjMxMTUxOTIvMzU1NzY5NjAzLTJlNWNkZTkwLTdmZjQtNGMxMS1iNTIzLTM3ODM1NjBlNzFjOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxMDEzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWY4NDA3YzdlOTY0ODg0ZDRkNjc4ZWI1ZGQ5YjJhOGZlZGEyMDY5MmUxNzQzMjdiZmRkMGEyNzhiMmFjYzVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8jYIFlzXpX6mPcU_VnMwY0zqXAo3E73OpQMaQVP-l-Q) ![IMG_20240807_175936](https://private-user-images.githubusercontent.com/123115192/355769625-ba023866-5622-45e9-95a2-a783316b23e6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjU4ODYsIm5iZiI6MTcyMzAyNTU4NiwicGF0aCI6Ii8xMjMxMTUxOTIvMzU1NzY5NjI1LWJhMDIzODY2LTU2MjItNDVlOS05NWEyLWE3ODMzMTZiMjNlNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxMDEzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wY2FiMWVjZTAxYTNjZDNlZTM1ZTI0OWNhZjgzZjg5YTVjODRhNDU3ZDg3ODc4NTk5YzI0MDZkMzBkNDBkNTlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4ePMGW2sPUul2VSXFb0ofIVWjUdecm0QJL4GA1-bHVg)

I mean switching between custom virtual mice within the game

**Comment by dudjv** [comment]
> 只需要将此映射键添加到控制布局中，即可动态切换虚拟鼠标。 ![IMG_20240807_175921](https://private-user-images.githubusercontent.com/123115192/355769603-2e5cde90-7ff4-4c11-b523-3783560e71c9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjU4ODYsIm5iZiI6MTcyMzAyNTU4NiwicGF0aCI6Ii8xMjMxMTUxOTIvMzU1NzY5NjAzLTJlNWNkZTkwLTdmZjQtNGMxMS1iNTIzLTM3ODM1NjBlNzFjOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxMDEzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWY4NDA3YzdlOTY0ODg0ZDRkNjc4ZWI1ZGQ5YjJhOGZlZGEyMDY5MmUxNzQzMjdiZmRkMGEyNzhiMmFjYzVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8jYIFlzXpX6mPcU_VnMwY0zqXAo3E73OpQMaQVP-l-Q) ![IMG_20240807_175936](https://private-user-images.githubusercontent.com/123115192/355769625-ba023866-5622-45e9-95a2-a783316b23e6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjU4ODYsIm5iZiI6MTcyMzAyNTU4NiwicGF0aCI6Ii8xMjMxMTUxOTIvMzU1NzY5NjI1LWJhMDIzODY2LTU2MjItNDVlOS05NWEyLWE3ODMzMTZiMjNlNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxMDEzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wY2FiMWVjZTAxYTNjZDNlZTM1ZTI0OWNhZjgzZjg5YTVjODRhNDU3ZDg3ODc4NTk5YzI0MDZkMzBkNDBkNTlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4ePMGW2sPUul2VSXFb0ofIVWjUdecm0QJL4GA1-bHVg)

![Screenshot_2024-08-07-18-18-13-01_157888a6fcdf6147cb3f40e862978649](https://github.com/user-attachments/assets/a11cecae-870e-4be7-b4e7-48927215d32e)
this
