### ISSUE TITLE
[BUG] Trying to add buttons that have two letters together

### ISSUE THREAD

**Issue by SkyBlee** [MovTery/PojavZenithHorizon#108]
### Issue Description

I'm trying to add buttons that have variations but I'm not getting an example of the quotes or ""

### Log File

.

### Screenshots or Videos

https://github.com/user-attachments/assets/5b7ad99f-2a36-4f14-a014-f9884edece10

### Reproduction Steps

```markdown
1. Open the Zenith pokav and create a button in the layout and try adding the button quotes or "" , or you can try placing the buttons with variations like /
```

### Expected Behavior

Failed to separate buttons with variant

### Android Version

14

### Pojav Zenith Horizon Version

1.2.6

### Additional Information

```markdown
.
```

### This issue has not been reported before

- [X] I have checked the Issues and found no similar issue reported

**Comment by MovTery** [comment]
This is not a bug, as in the game, this key has only one unique key value, even though it might appear to represent two different characters simultaneously.

**Comment by SkyBlee** [comment]
So how could I add the buttons?

**Comment by Vera-Firefly** [comment]
https://github.com/user-attachments/assets/7191fb70-2903-4c77-a3d9-9b287f9600e9
Set it up like this
