### ISSUE TITLE
My pojav launcher isn't opening 我的 pojav 启动器无法打开 

### ISSUE THREAD

**Issue by Coolboy42-89** [MovTery/PojavZenithHorizon#111]
### Issue Type

Game Issue

### Issue Description

My pojav launcher crashes upon opening 我的 pojav 启动器在打开时崩溃

### Log File

[latestcrash.txt](https://github.com/user-attachments/files/16602067/latestcrash.txt)

### Screenshots or Videos

![Screenshot_20240813-204811](https://github.com/user-attachments/assets/b3cf9c17-fe69-4c2e-b439-32ea391f258a)

### Reproduction Steps

```markdown
1. Open Pojav launcher
2. It crashes instantly
```

### Expected Behavior

My pojav launcher was working fine until i executed an optifine jar file. That isnt supposed to crash it.

### Android Version

10

### Pojav Zenith Horizon Version

1.2.7.1

### Additional Information

```markdown
- Device Model:Infinix hot 9
- CPU Architecture:arm64
- GPU Information:Power Vr rouge
```

### This issue has not been reported before

- [X] I have checked the Issues and found no similar issue reported

**Comment by MovTery** [comment]
@Coolboy42-89 
Please try using another file manager app to delete the launcher configuration file: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.zh/files/.minecraft/launcher_profiles.json
The data structure in this file seems to be corrupted, causing the launcher to fail to recognize it properly, which leads to crashes. Deleting this file will allow the launcher to regenerate a default configuration file.

This file is mainly used to record the current game instances within the launcher. Deleting this file will result in the loss of your game instance data, but game resources will not be affected.

**Comment by MovTery** [comment]
Uh, I mean, only the information about game instances will be lost; your game data will not be affected. For example, your downloaded Minecraft, game saves, mods, and other related data will still be intact.

**Comment by Coolboy42-89** [comment]
@MovTery  Thanks very much ❤❤
Love from Pakistan

**Comment by Coolboy42-89** [comment]
> Uh, I mean, only the information about game instances will be lost; your game data will not be affected. For example, your downloaded Minecraft, game saves, mods, and other related data will still be intact.

I got it lol 😂 Thanks
