### ISSUE TITLE
Other login feature(Authentication Server)

### ISSUE THREAD

**Issue by Ambientfish** [MovTery/PojavZenithHorizon#112]
### Feature Description

Would you like to add this feature, cuz I wanna login using littleskin.cn :)

(Just as like Pojav glow worm)

### Additional Information

![Screenshot_20240816-061121~2](https://github.com/user-attachments/assets/214f56ce-c3fe-4657-8a64-cc796e410e12)
![Screenshot_20240816-061116](https://github.com/user-attachments/assets/15b06cf1-cf8b-4870-a709-76a4a9b5db47)

### This feature request has not been proposed before

- [X] I have checked the Issues and found no similar feature request

**Comment by gumen2258** [comment]
https://github.com/user-attachments/assets/61efd1d8-7184-4246-be2c-1d67226968aa

这个功能本来就有("▔□▔)

**Comment by Ambientfish** [comment]
Thx a lot ^⁠_⁠_⁠_⁠_⁠_⁠_⁠_⁠_⁠_⁠^

**Comment by Ambientfish** [comment]
![Screenshot_20240817-175040.jpg](https://github.com/user-attachments/assets/45698fad-d2d9-4938-a703-debc77dda735)

I think that i need the universal apk
It does not work

**Comment by gumen2258** [comment]
你更新一下版本试试

**Comment by gumen2258** [comment]
> ![Screenshot_20240817-175040.jpg](https://github.com/user-attachments/assets/45698fad-d2d9-4938-a703-debc77dda735)
> 
> I think that i need the universal apk
> It does not work

你更新一下版本试试

**Comment by MovTery** [comment]
@Ambientfish The feature has always existed, but I only made it available to Chinese players. This is because the feature is quite controversial for non-Chinese players, and I don't think I can handle such controversy.

**Comment by MovTery** [comment]
I am Chinese, and I'm not entirely sure how non-Chinese players perceive this feature. If you know and are certain that most people are open to it, I am more than willing to lift this regional restriction.

**Comment by Ambientfish** [comment]
@MovTery Sure, I told my homies about Pojav, but they been asking me how to add skins & capes to it, it's rlly a good thing to add this "Major" feature to the project :)

btw I'm from Morocco.

**Comment by Ambientfish** [comment]
Can't wait!

**Comment by gumen2258** [comment]
> Can't wait!

You can download it in "Actions"

**Comment by CalvinJames9991** [comment]
How?

**Comment by Ambientfish** [comment]
Via littleskin.cn
