### ISSUE TITLE
[BUG] Brief Description pojav black screen in background

### ISSUE THREAD

**Issue by Coolboy42-89** [MovTery/PojavZenithHorizon#118]
### Issue Type

Game Issue

### Issue Description

pojav black screen in background

### Log File

[2024-07-13-1.log.gz](https://github.com/user-attachments/files/16714806/2024-07-13-1.log.gz)

### Screenshots or Videos

![Screenshot_20240822-210955](https://github.com/user-attachments/assets/82561b06-d16e-4679-a223-486e0d515d99)
![Screenshot_20240822-211006](https://github.com/user-attachments/assets/b3ca484f-f1bd-4e86-9925-57fac7232440)

### Reproduction Steps

```markdown
1. Open pojav
2.start game
3.put in background
3.its a black screen when opened again
```

### Expected Behavior

No black screen

### Android Version

10

### Pojav Zenith Horizon Version

1.2.8

### Additional Information

```markdown
- Device Model:Infinix hot 9
- CPU Architecture:arm 64
- GPU Information: Power vr
```

### This issue has not been reported before

- [X] I have checked the Issues and found no similar issue reported

**Comment by Muhammad90Emon** [comment]
did you used any type of mods?

**Comment by Coolboy42-89** [comment]
> did you used any type of mods?

With and without mods it happens

**Comment by agent1243** [comment]
I already had this error, and I solved it by putting "false" in fml.toml in the game's config folder
