### ISSUE TITLE
重新添加VirGLRenderer渲染器

### ISSUE THREAD

**Issue by jingzuiaiyao** [MovTery/PojavZenithHorizon#120]
### Feature Description

我希望建议重新添加VirGLRenderer渲染器选项。

原因：
1. 对于天玑处理器设备，VirGLRenderer通常能提供更好的性能。
2. 一些天玑处理器不支持Zink渲染器，VirGLRenderer可以作为有效替代。
3. 增加渲染选项可以提高启动器对不同硬件的适应性。

### This feature request has not been proposed before

- [X] I have checked the Issues and found no similar feature request

**Comment by gumen2258** [comment]
https://github.com/Vera-Firefly/PZH-X-PGW

这个是PojavZenitHorizon的魔改版，主要添加了一些渲染器，让用户有更多的选择。
