### ISSUE TITLE
[BUG] 外置登录“无效的会话”

### ISSUE THREAD

**Issue by ShulkerSakura** [MovTery/PojavZenithHorizon#127]
### 问题类型

游戏问题

### 问题描述

使用外置登录（littleskin）账户连接使用同一个外置认证服务器的多人游戏时，提示无效的会话，无法使用外置登录进行多人游戏（未关闭认证的）。

### 日志文件

[Uploading latest.log…]()

### 预期行为

能够使用外置登录与好友正常联机（不用关闭账户认证或额外安装mod绕过验证）

### Android 版本

14

### Pojav Zenith Horizon 版本

1.2.7.1

### 其他信息

```markdown
- 设备型号：
- CPU 架构：
- GPU 信息：
```

### 这个问题还没有人反馈过

- [X] 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by MovTery** [comment]
https://github.com/MovTery/PojavZenithHorizon/actions/runs/10823534660

**Comment by ShulkerSakura** [comment]
经测试依旧“无效的会话”
![Screenshot_2024-09-12-12-10-02-56_157888a6fcdf6147cb3f40e862978649](https://github.com/user-attachments/assets/ebf907bd-dcda-42eb-b0c4-c15c9d3e04bc)

**Comment by ShulkerSakura** [comment]
启动器日志与游戏日志：
[latestlog.txt](https://github.com/user-attachments/files/16973264/latestlog.txt)
[logs.zip](https://github.com/user-attachments/files/16973270/logs.zip)

**Comment by MovTery** [comment]
抱歉，我忘记保存这个关键的令牌了

**Comment by MovTery** [comment]
https://github.com/MovTery/PojavZenithHorizon/actions/runs/10824357117

**Comment by ShulkerSakura** [comment]
问题还在
![Uploading Screenshot_2024-09-12-13-22-17-88_157888a6fcdf6147cb3f40e862978649.jpg…]()

**Comment by MovTery** [comment]
你是否尝试过删除当前登录的账号重新登陆？Client Token需要重新登陆以刷新

**Comment by ShulkerSakura** [comment]
删除后重新添加了账户，问题依旧
![Screenshot_2024-09-12-13-48-59-24_157888a6fcdf6147cb3f40e862978649](https://github.com/user-attachments/assets/c322a295-320f-4711-bba4-bf9e57e699fb)

**Comment by ShulkerSakura** [comment]
请问是否需要连接我的服务器测试以排查问题？如有需要+Q 2531493755

**Comment by Mohammed444-ctrl** [comment]
> 你是否尝试过删除当前登录的账号重新登陆？Client Token需要重新登陆以刷新

Please update the pojav zenith horizon i love this application

**Comment by MovTery** [comment]
@ShulkerSakura 请尝试使用最新的构建版本，检查问题是否已经成功被修复

**Comment by ShulkerSakura** [comment]
Copy that

**Comment by ShulkerSakura** [comment]
问题已成功解决，开发者辛苦了
