### ISSUE TITLE
[BUG] 添加了一些模组后我的游戏就崩了

### ISSUE THREAD

**Issue by CookieCN36** [MovTery/PojavZenithHorizon#129]
### 问题类型

游戏问题

### 问题描述

呃呃，我准备开一个存档并且加一些模组，我总共加了这些模组:
[Forge Config API Port] ForgeConfigAPIPort-v21.0.8-1.21-Fabric

[Just Enough Items (JEI)] jei-1.21-fabric-19.8.2.99

[Open Parties and Claims] open-parties-and-claims-fabric-1.21-0.23.2

[Xaero的小地图] Xaeros_Minimap_24.4.0_Fabric_1.21

[文本占位符 API] placeholder-api-2.4.1+1.21

[更多动画] notenoughanimations-fabric-1.7.5-mc1.21

[模组菜单] modmenu-11.0.1

使用的模组加价器为Fabric
使用的渲染器为Holy GL4ES
游戏版本为1.21
JAVA版本为JAVA 21
给了他1536的RAM

### 日志文件

[latestlog.txt](https://github.com/user-attachments/files/16913643/latestlog.txt)

### 截图或视频

由于应用当前限制无法截图.........

### 复现步骤

```markdown
1.添加问题描述中的模组
2.启动游戏
3.下载所需要的文件（已经下载过一次）
4.游戏崩溃来到崩溃页面
```

### 预期行为

应该是正常启动游戏

### Android 版本

13

### Pojav Zenith Horizon 版本

1.2.9.1

### 其他信息

```markdown
GPU 制造商  : Qualcomm
GPU 渲染器  : Adreno (TM) 620
GPU 使用率  : 55%
刷新率      : 90 Hz
OpenGL ES 版本 : 3.2
GPU 版本    : I593c16c433, 1632727329 (Date: 09/27/21)
手机型号：IQOO Z3
```

### 这个问题还没有人反馈过

- [X] 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by MovTery** [comment]
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install fabric-api, version 0.100.8+1.21 or later.
	 - Install fabric, any version.
More details:
	 - Mod 'Forge Config API Port' (forgeconfigapiport) 21.0.8 requires version 0.100.7 or later of fabric-api, which is missing!
	 - Mod 'Just Enough Items' (jei) 19.8.2.99 requires version 0.100.8+1.21 or later of fabric-api, which is missing!
	 - Mod 'Mouse Tweaks' (mousetweaks) 2.26 requires any version of fabric-api, which is missing!
	 - Mod 'NotEnoughAnimations' (notenoughanimations) 1.7.5 requires any version of fabric-api, which is missing!
	 - Mod 'Open Parties and Claims' (openpartiesandclaims) 0.23.2 requires any version of fabric, which is missing!
	 - Mod 'Xaero's Minimap' (xaerominimap) 24.4.0 requires version 0.43.1 or later of fabric-api, which is missing!



你需要安装Fabric api模组
