### ISSUE TITLE
[BUG] Pojav crashes at creating a new forge profile

### ISSUE THREAD

**Issue by ARG-DT** [MovTery/PojavZenithHorizon#133]
### Issue Type

Application Issue

### Issue Description

When trying to create a new profile which any version of Minecraft in the process of downloading, forge, it crashes with error code 17.

### Log File

Here u have the log :
[latestlog.txt](https://github.com/user-attachments/files/16966519/latestlog.txt)

### Screenshots or Videos

Uhh, it's a crash so IDK what to put in here

### Reproduction Steps

```markdown
1. Open the launcher
2. Create a new profile (any version does the same, but I downloaded the log of a try with this characteristics version 1.20.1, forge 47.3.7)
3. Select any JRE (it crashes with anyone)
4. Wait or download forge (it crashes even if you don't do anything)
5. Crashes at error code 17
```

### Expected Behavior

Do not to crash when downloading forge even if you don't do anything

### Android Version

11

### Pojav Zenith Horizon Version

1.2.9.1

### Additional Information

```markdown
- Device Model: Redmi Note 9
- CPU Architecture: arm64-v8a
- GPU Information: Bifrost

- EXTRA 1:
I have been doing tests with different versions of forge, and it crashes with ANY version of minecraft forge.

- EXTRA 2:
Vanila versions works fine --- WAIT WHAT --- I found that when you close minecraft vanilla it crashes with the same error code (error code 17) so it could be related!

-EXTRA 3:
I have been reading the log and I found that it could be some sort of time thing like it depends on where you live (I live in Spain, so maybe that's the problem or something) or that's what the log says.
```

### This issue has not been reported before

- [X] I have checked the Issues and found no similar issue reported

**Comment by Muhammad90Emon** [comment]
have you used jre 17 ?

**Comment by ARG-DT** [comment]
> https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/tag/jre17-ec28559
> 
> have you used jre 17?

I will try it

**Comment by ARG-DT** [comment]
> https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/tag/jre17-ec28559
> 
> have you used jre 17?

IDK how to download, I am in a mobile phone not an emulator or something

**Comment by ARG-DT** [comment]
> https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/tag/jre17-ec28559
> 
> have you used jre 17?

if you're refering to the selection menu in pojav next you select the version of forge, it doesn't works with any jre

**Comment by Muhammad90Emon** [comment]
> > https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/tag/jre17-ec28559
> > have you used jre 17?
> 
> IDK how to download, I am in a mobile phone not an emulator or something and my phone doesn't have intel

umm, you should search it on youtube
