### ISSUE TITLE
"[BUG] wont login on my microsoft account".

### ISSUE THREAD

**Issue by DAVI30108** [MovTery/PojavZenithHorizon#136]
### Issue Type

Application Issue

### Issue Description

I'm having trouble logging into my Microsoft account via Zenith Horizon 

### Log File

java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:296)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:89)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

### Screenshots or Videos

![Screenshot_20240916-150112](https://github.com/user-attachments/assets/3fa0677e-737a-4950-a87e-5c3a4e7f8600)

### Android Version

14

### Pojav Zenith Horizon Version

1.3.0

### Additional Information

```markdown
- Device Model:
- CPU Architecture:
- GPU Information:
```

### This issue has not been reported before

- [X] I have checked the Issues and found no similar issue reported

**Comment by MovTery** [comment]
The launcher has already informed you that a long period of not logging into your Minecraft account may prevent the launcher from properly retrieving your account information. You need to log in again on the Minecraft official website. This issue commonly occurs with accounts that are not logged in through the official Minecraft launcher.

**Comment by DAVI30108** [comment]
> I've already tried doing this and it still didn't work.

**Comment by MovTery** [comment]
> > I've tried doing this and it still didn't work And now it's showing that I don't have a Minecraft profile我试过了，但还是不行，现在显示我没有我的个人资料
> > ![Screenshot_20240916-210428~2](https://private-user-images.githubusercontent.com/181774275/367962692-290df0cc-e444-4644-a315-f1987d95bb03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NDU0NTUsIm5iZiI6MTcyNjU0NTE1NSwicGF0aCI6Ii8xODE3NzQyNzUvMzY3OTYyNjkyLTI5MGRmMGNjLWU0NDQtNDY0NC1hMzE1LWYxOTg3ZDk1YmIwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QwMzUyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjU2MzE1YTQ2ZWY1ZmM4MWMyOGI4ODkwM2E3YmNkMDNhOWZmZTdhMTU1ODM4YzQ3MGFlYzJmYTg2NDBiZmUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BI76FJ1_zGGr6uAiirg5TwIQmsV1L0msfirKZI9cRuw)

Wait, have you purchased Minecraft with your Microsoft account?

**Comment by DAVI30108** [comment]
> Yes, I bought it, it worked here bro, just wait, sorry for taking up your time 😟

**Comment by DAVI30108** [comment]
> Yes I did, it worked here, I just had to wait, thank you very much for your help and sorry for taking up your time

**Comment by HUNTER7577** [comment]
Ibrahim

**Comment by HUNTER7577** [comment]
![Screenshot_2024-10-22-18-47-15-560_net kdt pojavlaunch zh](https://github.com/user-attachments/assets/e452f0c2-82bd-41d4-991a-b073ba292b70)
