### ISSUE TITLE
[BUG] Code -1

### ISSUE THREAD

**Issue by DAVI30108** [MovTery/PojavZenithHorizon#139]
### Issue Type

Game Issue

### Issue Description

I was playing survival normally and when I broke a rock that was on top of a cave the Launcher crashed automatically.

### Log File

[latestlog.txt](https://github.com/user-attachments/files/17051193/latestlog.txt)

### Screenshots or Videos

I couldn't take a screenshot because everything was black.

### Reproduction Steps

```markdown
1. I opened the Launcher
2. I opened the world
3. I broke a rock
4. It crashed
```

### Android Version

14

### Pojav Zenith Horizon Version

1.3.0.1

### Additional Information

```markdown
- Device Model:
- CPU Architecture:
- GPU Information:
```

### This issue has not been reported before

- [X] I have checked the Issues and found no similar issue reported

**Comment by MovTery** [comment]
It seems that you are using the Continuity Mod along with the Sodium Mod. However, the author of Continuity has clearly stated that if you use the Sodium Mod, you also need to install the Indium Mod; otherwise, compatibility issues may occur.

**Comment by DAVI30108** [comment]
> Parece que você está usando o Mod Continuity junto com o Mod Sodium. No entanto, o autor do Continuity afirmou claramente que se você usar o Mod Sodium, também precisará instalar o Mod Indium, caso contrário, poderão ocorrer problemas de compatibilidade.
Is that the only problem?
