### ISSUE TITLE
Bug Game

### ISSUE THREAD

**Issue by Lest-Try** [MovTery/PojavZenithHorizon#144]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

When I click Menu Launcher,Experimental,Miscellaneous settings Is crash PLEASE FIX

### Log File / 日志文件

IS CRASH IDK

### Screenshots or Videos / 截图或视频

IS CRASH IDK

### Reproduction Steps / 复现步骤

```markdown
IDK
```

### Expected Behavior / 预期行为

IDK

### Android Version / Android 版本

11

### Selected Renderer / 选择的渲染器

Holy GL4ES

### App Version / 应用版本

1.3.1

### Additional Information / 其他信息

Infinix Hot11s, Android 11,armb64

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by MovTery** [comment]
Please share your launcher log file as shown in the image below, as this will help me troubleshoot the issue.

![IMG_20240921_144038](https://github.com/user-attachments/assets/453b5386-eef4-4808-a1c4-068f49924b46)
![IMG_20240921_144053](https://github.com/user-attachments/assets/14b0c362-503a-4862-a87f-34aba3e3c719)

**Comment by Lest-Try** [comment]
Okeh bro

**Comment by Lest-Try** [comment]
[latestcrash.txt](https://github.com/user-attachments/files/17083198/latestcrash.txt)

**Comment by MovTery** [comment]
I have confirmed this issue, and I will fix the bug as soon as possible.

**Comment by Lest-Try** [comment]
Oke bro
