### ISSUE TITLE
Forge Install error

### ISSUE THREAD

**Issue by ThatOneSheep** [MovTery/PojavZenithHorizon#146]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

An error has occured while I was installing Forge 1.20.1 Build 47.3.0

### Log File / 日志文件

No log file

### Screenshots or Videos / 截图或视频

![Screenshot_20240921_175137_net kdt pojavlaunch zh](https://github.com/user-attachments/assets/15c2d0de-c4d4-4e8e-80de-56fccdd03428)

### Reproduction Steps / 复现步骤

```markdown
?
```

### Expected Behavior / 预期行为

?

### Android Version / Android 版本

10

### Selected Renderer / 选择的渲染器

Holy GL4ES

### App Version / 应用版本

1.3.1

### Additional Information / 其他信息

Huawei P30 Lite, Android 10, arm64-v8a

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by MovTery** [comment]
Please try again using JRE 8.
