### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by Kartvya69** [MovTery/PojavZenithHorizon#156]
### Feature Description / 功能描述

I was thinking of adding a custom resource pack downloader just like the mods downloader and when quitting the game in Minecraft should just open the launcher rather than the crash log and the crash log should give some errors codes to remove which mod to let the minecraft don't crash 

### This feature request has not been proposed before / 这个功能建议还没有人提出过

- [X] I have checked the Issues and found no similar feature request / 我已经查看过 Issues，并且没有发现与之类似的功能建议被提出

**Comment by Dorian12192** [comment]
Yes, that we want
