### ISSUE TITLE
Really annoying thing that always happens to me everytime i enter with 1.14.4 fabric modded

### ISSUE THREAD

**Issue by Smiilly768** [MovTery/PojavZenithHorizon#158]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

I have 3 optimization mods loaded and fabric api + MM (mod menu) everytime i launch it gets me to the bug thing and says the application game exited with 1/code idk what to do.

### Log File / 日志文件

[latestlog.txt](https://github.com/user-attachments/files/17246942/latestlog.txt)

### Android Version / Android 版本

15

### App Version / 应用版本

1.3.2.3

### Selected Renderer / 选择的渲染器

Holy GL4ES

### Device Information / 设备信息

TECNO SPARK 10

### This issue has not been reported before / 这个问题还没有人反馈过

- [ ] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by gumen2258** [comment]
原因是memoryleakfix模组的Mixin应用出现严重错误。
- 需要检查memoryleakfix模组或寻找替代方案以解决内存泄漏问题。
- 确保所有依赖库都正确加载，特别是libtinyiconv.so，它似乎缺失或未正确配置

**Comment by gumen2258** [comment]
原因是memoryleakfix模组的Mixin应用出现严重错误。
- 需要检查memoryleakfix模组或寻找替代方案以解决内存泄漏问题。
- 确保所有依赖库都正确加载，特别是libtinyiconv.so，它似乎缺失或未正确配置原因是memoryleakfix模组的Mixin应用出现严重错误。
- 需要检查memoryleakfix模组或寻找替代方案以解决内存泄漏问题。
- 确保所有依赖库都正确加载，特别是libtinyiconv.so，它似乎缺失或未正确配置
