### ISSUE TITLE
Bug Mods Sodium

### ISSUE THREAD

**Issue by Lest-Try** [MovTery/PojavZenithHorizon#161]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

When I Create a World With Sodium Mod It Crashes

### Log File / 日志文件

[latest.log](https://github.com/user-attachments/files/17267687/latest.log)

### Screenshots or Videos / 截图或视频

No is Crash

### Reproduction Steps / 复现步骤

```markdown
1.Download Fabric Version 0.16.0
2.And Install Mod sodium 
3.Create a world and it will crash
```

### Android Version / Android 版本

11

### App Version / 应用版本

1.3.3

### Selected Renderer / 选择的渲染器

Holy GL4ES

### Device Information / 设备信息

Infinix Hot11s, Android 11, arm64

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by Vera-Firefly** [comment]
Check your Internet and try to download Minecraft and sodium again

**Comment by Lest-Try** [comment]
I did it bro but it still crashes when creating a world

**Comment by Lest-Try** [comment]
I've used all renderers but it still crashes

**Comment by Lest-Try** [comment]
It works well but what if the Pojav Launcher ZH application is updated?

**Comment by Lest-Try** [comment]
Still crashing bro

**Comment by Lest-Try** [comment]
here bro 
[latest.log](https://github.com/user-attachments/files/17268910/latest.log)

**Comment by Lest-Try** [comment]
Here bro 
[latestlog.txt](https://github.com/user-attachments/files/17269182/latestlog.txt)

**Comment by Lest-Try** [comment]
So what bro?
