### ISSUE TITLE
Game crashing when I start 

### ISSUE THREAD

**Issue by OverScarf** [MovTery/PojavZenithHorizon#169]
### Issue Type / 问题类型

Application Issue / 应用问题

### Issue Description / 问题描述

When I was try to lauch the game it's crashing 
I don't know why the crashing started from the pojav zenith horizon 1.3.0+ version
[latestlog.txt](https://github.com/user-attachments/files/17323734/latestlog.txt)

### Log File / 日志文件

[latestlog.txt](https://github.com/user-attachments/files/17323742/latestlog.txt)

### Screenshots or Videos / 截图或视频

https://github.com/user-attachments/assets/e9071c7d-7759-464b-8e35-65a674d96b14

### Reproduction Steps / 复现步骤

```markdown
The log show last starting libvm.so and crashes
```

### Android Version / Android 版本

13

### App Version / 应用版本

1.3.4

### Selected Renderer / 选择的渲染器

Holy GL4ES

### Device Information / 设备信息

Poco F1 android13 arm64

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by MovTery** [comment]
Please try turning off this setting.

![IMG_20241010_153006](https://github.com/user-attachments/assets/2b611e37-6cae-4ad0-821b-4a7521947178)

**Comment by OverScarf** [comment]
Still crashing but not the same error

**Comment by OverScarf** [comment]
> Please try turning off this setting.
> 
> ![IMG_20241010_153006](https://private-user-images.githubusercontent.com/123115192/375271668-2b611e37-6cae-4ad0-821b-4a7521947178.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NTY3NzEsIm5iZiI6MTcyODU1NjQ3MSwicGF0aCI6Ii8xMjMxMTUxOTIvMzc1MjcxNjY4LTJiNjExZTM3LTZjYWUtNGFkMC04MjFiLTRhNzUyMTk0NzE3OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxMDM0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjRmN2VkZGY5ZWJmNWQxMWUzM2RhZjQ4NWJiOWE3ZjA3ZDdlZTY4MWFkODU5YmVkNzdmODZmNmFhMmJjZjBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VxziEdNzJd_Gu1YDeJEBlMiEMGKQp_rGz9Npyms_xI0)

Bro new error above

**Comment by MovTery** [comment]
It seems that some Fabric files failed to install correctly. I will try to rewrite the Fabric installation mechanism to ensure no files are lost. This should take effect in the next version.
