### ISSUE TITLE
Can't allocate ram more than 1024 mb even though I have more free ram. 

### ISSUE THREAD

**Issue by ShoyebOP** [MovTery/PojavZenithHorizon#173]
### Issue Type / 问题类型

Application Issue / 应用问题

### Issue Description / 问题描述

I have a Samsung j8 device which has 4 gb ram and it has more than 2.2 gb ram free all the time but the game doesn't allow me to increase the ram allocation more than 1024 mb even it allows me to increase it to 1024 mb it crashes immediately (crash report is included) after starting the game to play i had to decrease it to 800 mb.

I have another device named OnePlus 5 where I can allocate ram up to 6840 mb (as it has 8 gb ram) even if I don't have that much ram free and if I attempt to play with that it gives me warning but still lets me play. But in Samsung j8 it crashes directly.

Now,
First of all it doesn't even allows me to allocate the full 2.2 gb free ram .

Secondly it even crashes if I give the max amount of allocated ram(1024 mb)

Thirdly it only allows me to play with 800 mb allocated ram which easily gets overloaded.

(This issue was previously reported on pojavlauncher repo and they said they are trying to fix it but it has been months and there's no response)

### Log File / 日志文件

[latestlog.txt](https://github.com/user-attachments/files/17356132/latestlog.txt)

### Reproduction Steps / 复现步骤

```markdown
1. Start pojavlauncher.
2. Go to Java tweaks settings.
3. Allocate 1024 mb ram.
4. Select any game profile and hit play.
5. The game will crash.

*I don't think it can be reproduced without specific devices but I still included it*
```

### Android Version / Android 版本

9

### App Version / 应用版本

1.3.5

### Selected Renderer / 选择的渲染器

None

### Device Information / 设备信息

Samsung Galaxy j8, android 9, armbi-v7a

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by MovTery** [comment]
I actually believe that devices running Android 8-9 have very strict memory management. If the allocated memory exceeds the available and free memory, the game will crash immediately, unlike devices running Android 10 or higher, which only crash due to insufficient memory when it is truly exhausted. So, this is not an issue with the launcher, but rather a problem with Android's memory management. Sorry, this is something I can't fix.

**Comment by ShoyebOP** [comment]
> I actually believe that devices running Android 8-9 have very strict memory management. If the allocated memory exceeds the available and free memory, the game will crash immediately, unlike devices running Android 10 or higher, which only crash due to insufficient memory when it is truly exhausted. So, this is not an issue with the launcher, but rather a problem with Android's memory management. Sorry, this is something I can't fix.

Thanks ❤️ for at least saying that it's not fixable , rather than giving me hope like rather someone,saying that its fixable and not responding ever again.
