### ISSUE TITLE
idk where the hell is angle renderer

### ISSUE THREAD

**Issue by S0SUKEAIZEN** [MovTery/PojavZenithHorizon#175]
### Issue Type / 问题类型

Application Issue / 应用问题

### Issue Description / 问题描述

i don't see the angle renderer in zenith 

### Log File / 日志文件

there is none.

### Android Version / Android 版本

13

### App Version / 应用版本

latest 

### Selected Renderer / 选择的渲染器

None

### Device Information / 设备信息

a77s android 13

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by Vera-Firefly** [comment]
LTW
