### ISSUE TITLE
will you guys upload the launcher on play store cuz there are alot of people who are having problem in installing the apk

### ISSUE THREAD

**Issue by CROSS7860** [MovTery/PojavZenithHorizon#187]
### Feature Description / 功能描述

Mostly people those who have a chromebook cannot install the apk

### This feature request has not been proposed before / 这个功能建议还没有人提出过

- [X] I have checked the Issues and found no similar feature request / 我已经查看过 Issues，并且没有发现与之类似的功能建议被提出

**Comment by MovTery** [comment]
I don't have any account to pay Google for registering a developer account.

**Comment by CROSS7860** [comment]
sad ):
