### ISSUE TITLE
运行实例1.12.2-forge以代码一退出

### ISSUE THREAD

**Issue by gumen2258** [MovTery/PojavZenithHorizon#77]
### 问题描述

所有渲染器都试过了，也没有加任何的模组
还是以代码1退出

### 日志文件

[latestlog.txt](https://github.com/user-attachments/files/16136960/latestlog.txt)

### 截图或视频

![Screenshot_20240709_105449_net kdt pojavlaunch zh](https://github.com/MovTery/PojavZenithHorizon/assets/136236969/d314b77c-402b-459a-82b0-38698fd3584b)

### 复现步骤

```markdown
1.打开启动器
2.启动游戏
3.以代码一退出
```

### 预期行为

![Screenshot_20240709_105449_net kdt pojavlaunch zh](https://github.com/MovTery/PojavZenithHorizon/assets/136236969/cd03eea8-f57f-49bd-8e0c-22d348e42a7e)

### Android 版本

9

### Pojav Zenith Horizon 版本

1.2.4.2

### 其他信息

```markdown
- 设备型号：HUAWEI Nova3
- CPU 架构：ARM64
- GPU 信息：mail-G72
```

### 这个问题还没有人反馈过

- [X] 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by MovTery** [comment]
@gumen2258 你使用的外置登录服务器返回了403异常，但是没有更多详细的信息，请自行检查你使用的外置登录服务器登录状态以及是否可用
![屏幕截图 2024-07-09 115604](https://github.com/MovTery/PojavZenithHorizon/assets/123115192/a9ca1304-2884-4a94-a446-8448e61f124d)

**Comment by gumen2258** [comment]
哦哦

**Comment by gumen2258** [comment]
> @gumen2258 你使用的外置登录服务器返回了403异常，但是没有更多详细的信息，请自行检查你使用的外置登录服务器登录状态以及是否可用
> ![屏幕截图 2024-07-09 115604](https://github.com/MovTery/PojavZenithHorizon/assets/123115192/a9ca1304-2884-4a94-a446-8448e61f124d)
> 

找到原因了，三克油
