### ISSUE TITLE
版本自定义图标

### ISSUE THREAD

**Issue by Rzdpai** [MovTery/PojavZenithHorizon#78]
### 问题描述

自定义图标只显示一半

### 日志文件

没有

### 截图或视频

半个图标

### 复现步骤

```markdown
修改图标
```

### 预期行为

显示完整的图标

### Android 版本

12

### Pojav Zenith Horizon 版本

1.2.4.2

### 其他信息

```markdown
- 设备型号：RealmeV30
- CPU 架构：arm64
- GPU 信息：天玑700
```

### 这个问题还没有人反馈过

- [ ] 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by Vera-Firefly** [comment]
https://github.com/MovTery/PojavZenithHorizon/issues/64
