### ISSUE TITLE
[BUG]Android SDK版本为25不能安装，请问是否有其他版本可以使用

### ISSUE THREAD

**Issue by massorant** [MovTery/PojavZenithHorizon#81]
### Problem Description

错误信息表明尝试安装的 APK 文件（PojavZenithHorizon-1.2.5.1.apk）需要更高版本的Android SDK 来运行，而我的设备（读书郎C5平板）当前的SDK版本是25，而 APK要求的文件是SDK版本26或更高。

### Log Files

(base) pointsun@pointsundeMacBook-Air ~ % adb install /Users/pointsun/Downloads/PojavZenithHorizon-1.2.5.1.apk
Performing Streamed Install
adb: failed to install /Users/pointsun/Downloads/PojavZenithHorizon-1.2.5.1.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl1875637084.tmp/base.apk (at Binary XML file line #7): Requires newer sdk version #26 (current version is #25)]

### Screenshots or Videos

<img width="844" alt="截屏2024-07-14 22 51 34" src="https://github.com/user-attachments/assets/16e97ca6-0bb0-476c-8a51-17fcc3e204e4">

### Steps to Reproduce

```markdown
读书郎C5，连接电脑使用adb安装PojavZenithHorizon-1.2.5.1.apk出现安装失败。
```

### Expected Behavior

APK 可能实际上并不需要 SDK 26 上运行，但 minSdkVersion 被错误地设置得太高。请求开发者修改 APK 的 minSdkVersion以让年老的设备运行PojavZenithHorizon。

### Android Version

7-

### Pojav Zenith Horizon Version

1.2.5.1

### Additional Information

```markdown
-设备型号：Readboy_C5Pro
- CPU架构：
Processor	: AArch64 Processor rev 4 (aarch64) arm64-v8a
processor	: 0
processor	: 1
processor	: 2
processor	: 3
processor	: 4
processor	: 5
processor	: 6
processor	: 7
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4
- GPU信息：
```

### This issue has not been reported by anyone else yet

- [X] I have checked the issues and have not found any similar reports

**Comment by MovTery** [comment]
应用使用到了SDK26的新特性，所以不再支持安卓7及以下设备
