### ISSUE TITLE
Java运行时无法删除[BUG] 简短的描述

### ISSUE THREAD

**Issue by Rzdpai** [MovTery/PojavZenithHorizon#82]
### 问题描述

删除java后下次启动会自动添加回来

### 日志文件

无

### 复现步骤

```markdown
1.删除JAVA
2重启启动器
```

### 预期行为

不会出现

### Android 版本

12

### Pojav Zenith Horizon 版本

1.2.5.1

### 其他信息

```markdown
- 设备型号：realmeV30
- CPU 架构：arm v8a
- GPU 信息：天玑700
```

### 这个问题还没有人反馈过

- [X] 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by MovTery** [comment]
因为那些是启动器默认的JRE，启动器每一次启动都会检查JRE，如有缺失默认的JRE就会补上，所以这不是BUG

**Comment by Rzdpai** [comment]
> 因为那些是启动器默认的JRE，启动器每一次启动都会检查JRE，如有缺失默认的JRE就会补上，所以这不是BUG

那能不能添加彻底删除的功能，JAVA17对我来说确实没什么用，或者像PojavLauncher一样单独一个没有运行时的版本
