### ISSUE TITLE
虚拟鼠标与实体鼠标指针切换

### ISSUE THREAD

**Issue by PickLeaf** [MovTery/PojavZenithHorizon#84]
### 功能描述

希望能添加一个开关，能在游戏内打开GUI界面时选择用虚拟机的鼠标指针还是用物理机的鼠标指针。
这样当我想操作物理机的界面时不用再傻乎乎地抬起手再放下了，比如关掉弹窗或更改音量。
Holy GL4ES的鼠标指针在我的设备上输入动量会不是线性的，更快的速度会导致更少的位移，鼠标滑得越快游标动的越慢。换成Adroid系统的鼠标指针就很正常了
pojav原版23年的release还是用物理机的指针，后来又改成用虚拟机的了，我都一直没更新

### 其他信息

https://github.com/user-attachments/assets/db427231-1502-42da-bfdc-517c779964b3

### 这个功能建议还没有人提出过

- [X] 我已经查看过 Issues，并且没有发现与之类似的功能建议被提出

**Comment by MovTery** [comment]
我会尝试修改这个功能的，敬请期待

**Comment by PickLeaf** [comment]
Zalith2已经有这个功能了，什么时候能同步到Zalith1啊，求求了😭😭😭
