### ISSUE TITLE
holy渲染器下帧率异常

### ISSUE THREAD

**Issue by thousand111** [MovTery/PojavZenithHorizon#85]
### 问题描述

设备红米k40，cpu是骁龙870，在所有设置均为默认设置下，以holy渲染器进入游戏，在进入世界后出现帧率异常现象最后（帧率仅为0~1），此现象在原版pojav启动器上并未发生过

### 日志文件

[latestlog.txt](https://github.com/user-attachments/files/16255554/latestlog.txt)

### 截图或视频

https://github.com/user-attachments/assets/84beaa36-8c33-4125-a83f-92ce9c3bb19c

### 复现步骤

```markdown
1打开启动器
2启动游戏版本为1.21
3进入游戏主界面
4进入世界
5发生异常
```

### Android 版本

14

### Pojav Zenith Horizon 版本

1.2.5.1

### 其他信息

```markdown
- 设备型号：Redmi k40
- CPU 架构：armv7
- GPU 信息：adreno650
```

### 这个问题还没有人反馈过

- [X] 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by MovTery** [comment]
骁龙处理器日常，不予修复
