### ISSUE TITLE
[BUG] 同步官方版本后，出现相似的渲染问题 (After synchronizing with the official version, similar rendering issues appeared)

### ISSUE THREAD

**Issue by AratakiZay** [MovTery/PojavZenithHorizon#91]
### 问题描述

When i play on my server and my world , it just Showing Like that, Im using My regular mods that I use on pojav, It just showing the shadow at Block, its like Blindness effect tho, ive trying to fix that but the shadow still showing, pls help me

### 日志文件

theres no Crash

### 截图或视频

![Screenshot_2024-07-21-08-26-58-998_com miui gallery](https://github.com/user-attachments/assets/0d0955be-c0ee-45f5-9c6d-0cf4b76ea8c3)
![Screenshot_2024-07-21-08-20-15-718_net kdt pojavlaunch zh](https://github.com/user-attachments/assets/e8523305-fce1-49ac-bab7-4aff3cf83d21)

### 复现步骤

```markdown
-login to pojav zenith
-play
-go to multiplayer
-when uts done
-it shows like that
```

### 预期行为

I hope U can Give Me How to fix this, bcs i feel Annoying by this shadow ;-;, And please Chat me with english

### Android 版本

14

### Pojav Zenith Horizon 版本

1.2.5.1

### 其他信息

```markdown
- 设备型号：Poco X6 5G
- CPU 架构：snapdragon 7s Gen 2 (Octa-core (4x2.40 GHz Cortex-A78 & 4x1.95 GHz Cortex-A55)
- GPU 信息：Adreno 710
```

### 这个问题还没有人反馈过

- [X] 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by MovTery** [comment]
@AratakiZay 
If you encounter this issue while using PojavLauncher, and not just on Pojav Zenith Horizon, please report it to the PojavLauncher Team. Since we didn't develop the renderer ourselves, we can't fix it. We are simply using the renderer they developed.

**Comment by AratakiZay** [comment]
@MovTery hi, its not pojavlauncher, thats pojav horizon, sorry for misunderstanding.

**Comment by AratakiZay** [comment]
@MovTery

**Comment by AratakiZay** [comment]
@MovTery im using fabric 1.21 With Sodium + iris, The shader wont work on pojavzenith, but on pojav launcher it work, Im using holy, And the shader is Mellow shader

**Comment by AratakiZay** [comment]
If u can help me how to fix this, pls help me, because i feel annoyed by the shadow, thx.

**Comment by Vera-Firefly** [comment]
Pojav does not suppor sodium

**Comment by Vera-Firefly** [comment]
If you want to use sodium on pojav, please use the fixed version of sodium

**Comment by AratakiZay** [comment]
> Pojav does not suppor sodium
So pojavzenith not work on sodium too?

**Comment by XianAqq** [comment]
![Screenshot_2024-07-22-16-27-17-26_157888a6fcdf6147cb3f40e862978649](https://github.com/user-attachments/assets/4ed4221b-8bed-4336-ad23-6ea98e0282d9)
When I put torches It comes out white, how to fix it?

**Comment by XianAqq** [comment]
![Uploading Screenshot_2024-07-25-10-08-18-74_157888a6fcdf6147cb3f40e862978649.jpg…]()
How to fix thissss???
