### ISSUE TITLE
更多渲染器

### ISSUE THREAD

**Issue by Rzdpai** [MovTery/PojavZenithHorizon#92]
### 功能描述

希望能够添加回virgl和mesa版本设置

### 这个功能建议还没有人提出过

- [X] 我已经查看过 Issues，并且没有发现与之类似的功能建议被提出

**Comment by MovTery** [comment]
由于其功能对于大部分设备而言，存在不稳定性，可能会导致游戏内锁1帧的问题，我决定不再支持这个功能

**Comment by Rzdpai** [comment]
> 由于其功能对于大部分设备而言，存在不稳定性，可能会导致游戏内锁1帧的问题，我决定不再支持这个功能

在我的设备上，angle不能开光影,zink闪退(之前的版本可以通过降低mesa版本来解决)，Open4ES&MKSF效果和优化都没有一些低配光影(如Chocapic13.V6.Lite)好，而且gl4es上使用iris(不加光影)会概率性出现黑线条(加了FabricAPI，一些服务器上则是100%出现这种情况)，只能删除iris，而且gl4es在高版本上bug也挺多的(如:极佳画质下水面可以透视，且无法渲染资源包中的光影(都是确定过OpenGL2.1可用的)，使用Continuity渲染连接纹理时泥土会变成纯色，渲染矿石发光时则是整个矿石全部发光(岩石部分也变成了矿石对应的颜色))而且PojavLauncher的另一个改版PojavGlowWorn使用virgl会闪退，官方版又取消了virgl，FoldCraftLauncher也是一样的情况

就算不能添加回去，可不可以添加自定义渲染器的选项(自行导入so文件)
