### ISSUE TITLE
[CRASH] Crashing Zenith Pojav

### ISSUE THREAD

**Issue by AllenPlayzMC** [MovTery/PojavZenithHorizon#93]
### Problem Description

Im crashing using the adreno renderer

### Log Files

[latestlog.txt](https://github.com/user-attachments/files/16365017/latestlog.txt)

### Screenshots or Videos

The crash happens when loading the game

### Steps to Reproduce

```markdown
Please fix thisssss
```

### Expected Behavior

Expected to load normally, but it crashed

### Android Version

13

### Pojav Zenith Horizon Version

1.2.3

### Additional Information

```markdown
- Device Model:CPH2375 / OPPO A76
- CPU Architecture: Qualcomm Snapdragon 680
- GPU Information:
GPU Renderer: Adreno (TM) 610 @ 1114 Mhz
GPU Vendor: Qualcomm
```

### This issue has not been reported by anyone else yet

- [X] I have checked the issues and have not found any similar reports

**Comment by Badr69420** [comment]
I have a snapdragon 680 and its not compatible freeadreno

**Comment by gumen2258** [comment]
The latest version of PojavZenitHorizon solves this problem from the root (the renderer is synchronized with the official one), and other renderers are removed (to improve game stability)😶

**Comment by AllenPlayzMC** [comment]
> The latest version of PojavZenitHorizon solves this problem from the root (the renderer is synchronized with the official one), and other renderers are removed (to improve game stability)😶

Can u put the link of latest version?

**Comment by AllenPlayzMC** [comment]
> I have a snapdragon 680 and its not compatible freeadreno

i thought snapdragon supports freedreno renderer:(

**Comment by gumen2258** [comment]
> > The latest version of PojavZenitHorizon solves this problem from the root (the renderer is synchronized with the official one), and other renderers are removed (to improve game stability)😶
> 
> Can u put the link of latest version?

You misunderstood what I meant. What I wanted to say is that the Snapdragon 680 can no longer enable lighting and shadow in the new version. The only renderer that can enable lighting and shadow is zink, and your processor obviously does not support this renderer.

**Comment by AllenPlayzMC** [comment]
> > > The latest version of PojavZenitHorizon solves this problem from the root (the renderer is synchronized with the official one), and other renderers are removed (to improve game stability)😶
> > 
> > 
> > Can u put the link of latest version?
> 
> You misunderstood what I meant. What I wanted to say is that the Snapdragon 680 can no longer enable lighting and shadow in the new version. The only renderer that can enable lighting and shadow is zink, and your processor obviously does not support this renderer.

Ohhh okayyy, i understand

**Comment by AllenPlayzMC** [comment]
> > > The latest version of PojavZenitHorizon solves this problem from the root (the renderer is synchronized with the official one), and other renderers are removed (to improve game stability)😶
> > 
> > 
> > Can u put the link of latest version?
> 
> You misunderstood what I meant. What I wanted to say is that the Snapdragon 680 can no longer enable lighting and shadow in the new version. The only renderer that can enable lighting and shadow is zink, and your processor obviously does not support this renderer.

So my phone ran Fabric 1.20.1 using Zenith 1.2.5.5 but the thing is there is a delay when pressing the buttons in game

**Comment by gumen2258** [comment]
“钠”的原因

**Comment by AllenPlayzMC** [comment]
> “钠”的原因

what do u mean?

**Comment by gumen2258** [comment]
> > “钠”的原因
> 
> what do u mean?

Probably because of the mod "Sodium".

**Comment by AllenPlayzMC** [comment]
> > > “钠”的原因
> > 
> > 
> > what do u mean?
> 
> Probably because of the mod "Sodium".

Why is it because of sodium?

**Comment by gumen2258** [comment]
> > > > “钠”的原因
> > > 
> > > 
> > > what do u mean?
> > 
> > Probably because of the mod "Sodium".
> 
> Why is it because of sodium?

Because mod sodium and Pojavlauncher often have problems

**Comment by AllenPlayzMC** [comment]
> > > > “钠”的原因
> > > 
> > > 
> > > what do u mean?
> > 
> > 
> > Probably because of the mod "Sodium".
> 
> Why is it because of sodium?

ohhhhh okkk
