### ISSUE TITLE
控制布局编辑器建议

### ISSUE THREAD

**Issue by Leowly** [MovTery/PojavZenithHorizon#94]
### 功能描述

在控制布局编辑器中增加一个选项，它可以更改自动吸附的最小间隔，原版的自动吸附默认是带有一小段距离的，有的时候非常不方便

### 这个功能建议还没有人提出过

- [X] 我已经查看过 Issues，并且没有发现与之类似的功能建议被提出

**Comment by MovTery** [comment]
![IMG_20240728_194535.jpg](https://github.com/user-attachments/assets/a42df772-c10d-4b88-b815-38ccf6b7fde0)

![IMG_20240728_194526.jpg](https://github.com/user-attachments/assets/9df57acf-f677-49cf-a495-69a1c8a91eb1)
