### ISSUE TITLE
加载模组后以代码-1退出

### ISSUE THREAD

**Issue by Smilesink0Chinese** [MovTery/PojavZenithHorizon#97]
### Problem Description

无论是Forge还是Fabric都是这样
Mojang红标跑完之后就-1退出

### Log Files

--------- beginning with launcher debug
Info: Launcher version: 1.2.5.7 (9940701)
Info: Architecture: arm64
Info: Device model: HUAWEI TGR-W00
Info: API version: 31
Info: Selected Minecraft version: fabric-loader-0.16.0-1.20.1
Info: Custom Java arguments: ""
Info: Java Runtime: Default
Added custom env: TMPDIR=/data/user/0/net.jdk.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2800
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~jsaZKPpfKymxZEkIsCLwow==/net.jdk.pojavlaunch-rJ5kT0AXeH2Zd4SyS14WYw==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.jdk.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.jdk.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.jdk.pojavlaunch/runtimes/Internal-17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.jdk.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.jdk.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~jsaZKPpfKymxZEkIsCLwow==/net.jdk.pojavlaunch-rJ5kT0AXeH2Zd4SyS14WYw==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.jdk.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.jdk.pojavlaunch/runtimes/Internal-17
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=1840
Initialising gl4es
v1.1.5 built on Jul 14 2024 19:34:14
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 16
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 8192
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is HUAWEI
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
2024-08-01 10:40:08,336 main ERROR appender Console has no parameter that matches element Policies
[10:40:08] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.16.0
[10:40:08] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[10:40:08] [main/INFO]: Loading 4 mods:
	- fabricloader 0.16.0
	   \-- mixinextras 0.4.0
	- java 17
	- minecraft 1.20.1
[10:40:08] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/storage/emulated/0/Android/data/net.jdk.pojavlaunch/files/.minecraft/libraries/net/fabricmc/sponge-mixin/0.15.0+mixin.0.8.7/sponge-mixin-0.15.0+mixin.0.8.7.jar Service=Knot/Fabric Env=CLIENT
[10:40:10] [main/WARN]: File not found or not readable: /proc/stat

### Steps to Reproduce

```markdown
1.打开启动器
2.创建新实例
3.创建资源包实例
4.搜索GANG120
5.启动实例并正常安装
6.启动游戏
7.MOJANG红标加载
8.以-1退出
```

### Android Version

14

### Pojav Zenith Horizon Version

12.5.7

### Additional Information

```markdown
- Device Model:HUAWEI TGR-W00(MatePad 11.5s)
- CPU Architecture:麒麟9000WM
- GPU Information:麒麟9000WM
```

### This issue has not been reported by anyone else yet

- [X] I have checked the issues and have not found any similar reports

**Comment by MovTery** [comment]
请提供完整的日志文件
