### ISSUE TITLE
Zink渲染器闪退

### ISSUE THREAD

**Issue by qqdasb** [MovTery/PojavZenithHorizon#98]
### 问题描述

Zink渲染器在我的设备上奔溃
GL4ES渲染器正常

### 日志文件

[latestlog-gl4es.txt](https://github.com/user-attachments/files/16451504/latestlog-gl4es.txt)
[latestlog-zink.txt](https://github.com/user-attachments/files/16451505/latestlog-zink.txt)

### 复现步骤

```markdown
1.编辑实例
2.把渲染器改成Zink
3.启动游戏
```

### Android 版本

9

### Pojav Zenith Horizon 版本

1.2.5.7

### 其他信息

```markdown
- 设备型号：Vivo X23
- CPU 架构：arm64-v8a
- GPU 信息：Adreno 615
```

### 这个问题还没有人反馈过

- [X] 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by MovTery** [comment]
并不是所有设备都支持使用 Zink 渲染器
